[electricload]
wifi_ssid = "<SSID>"
wifi_psk = "<PASSWORD>"
influxdb_server = "<InfluxDB IP>:8086"
pid_kp = "0.0000005"
pid_ki = "0.00002"
pid_kd = "0.05"
pwm_offset = "4500"
max_current_limit = "15.0"
max_power_limit = "105.0"
max_current_limit_ratio = "1.1"
under_voltage_limit = "0.1"
influxdb_api_key = "<API_KEY>"
influxdb_api = "/api/v2/write?org=<ORG>&bucket=LOGGER&precision=ns"
influxdb_tag = "currentch1"
influxdb_measurement = "electricload"